# docker-compose.yml
version: '3.8'
services:
  database:
    image: neo4j:latest
    env_file:
      - 'docker_env'
    volumes:
      - dbdata:/data
    ports:
      - '7474:7474'
      - '7687:7687'
      
volumes:
  dbdata: